export const defaultTheme = {
  colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorForFeature: "#E1EDCE",
  colorForFeatureNegative: "#F8DDD7",
  colorForFeatureOwner: "#88AA4D",
  colorForFeatureOwneNegative: "#F75531",
  colorForButton: "#FC9B27",
  colorForButtonHover: "#FC7427",
  pagePadding: "90px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  pageWidth: "1280px",
  indent: "20px",
  colorForabout: "#d8ecfe",
  lineHeightDefault: 1.5,
  backgroundColorGray: "#f7f7f7",
  headerHeight: "80px"
};
